---
cloudProvider: ionoscloud

autoscalingGroups:
  # Repeat for every node pool that should be scaled
  - name: # Put ID of node pool here
    minSize: 1
    maxSize: 3

extraEnv:
  IONOS_CLUSTER_ID: # Put ID of cluster here

extraEnvSecrets:
  IONOS_TOKEN:
    name: cloud-config
    key: token
