version: 2
updates:
- package-ecosystem: gomod
  directory: "/vertical-pod-autoscaler"
  schedule:
    interval: daily
  open-pull-requests-limit: 0 # setting this to 0 means only allowing security updates, see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
  labels:
    - "vertical-pod-autoscaler"
- package-ecosystem: docker
  directory: "/vertical-pod-autoscaler/pkg/recommender"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
  labels:
    - "vertical-pod-autoscaler"
- package-ecosystem: docker
  directory: "/vertical-pod-autoscaler/pkg/updater"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
  labels:
    - "vertical-pod-autoscaler"
- package-ecosystem: docker
  directory: "/vertical-pod-autoscaler/pkg/admission-controller"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
  labels:
    - "vertical-pod-autoscaler"
