apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-autoscaler-grpc-server-cert
  namespace: kube-system
spec:
  secretName: cluster-autoscaler-grpc-server-cert
  commonName: ca-external-grpc-cloud-provider-service
  duration: 87600h
  usages:
    - server auth
  dnsNames:
    - "ca-external-grpc-cloud-provider-service"
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
