apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-autoscaler-grpc-client-cert
  namespace: kube-system
spec:
  secretName: cluster-autoscaler-grpc-client-cert
  commonName: cluster-autoscaler-grpc-client
  dnsNames:
    - "cluster-autoscaler-grpc-client"
  duration: 87600h
  usages:
    - client auth
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
