apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
data:
  cloud.conf: |
    [Global]
      Zone=<region><az>
    [ServiceOverride "ec2"]
      Service=ec2
      Region=<region>
      URL=<endpoint_url>
      SigningRegion=<region>
    [ServiceOverride "autoscaling"]
      Service=autoscaling
      Region=<region>
      URL=<endpoint_url>
      SigningRegion=<region>
