cloudProvider: aws

autoscalingGroups:
  - name: aws-asg-name
    minSize: 1
    maxSize: 2

awsRegion: eu-west-1
awsAccessKeyID: "******"
awsSecretAccessKey: "******"

cloudConfigPath: config/cloud.conf

extraVolumes:
  - name: cloud-config
    configMap:
      name: cloud-config

extraVolumeMounts:
  - name: cloud-config
    mountPath: config

